---
- name: Download and install om-cli
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/pivotal-cf/om/releases/download/{{ om_version }}/om-linux-{{ om_version }}"
    dest: /usr/local/bin/om
    mode: '0755'

- name: om version
  shell: /usr/local/bin/om --version
  register: om_version_output
  changed_when: false

- name: show om version
  debug:
    msg: "{{ om_version_output.stdout }}"
