---
- hosts: all
  become: true
  vars:
    # check versions at https://builds.hex.pm/builds/elixir/builds.txt
    # mise_erlang_version: "27.3.4.12"
    # mise_elixir_version: "1.19.5-otp-27"
  roles:
    - { role: mise, tag: ["dev"] }
    - { role: mise-erlang, tag: ["dev"] }
