---
- name: Download and extract credhub directly to /usr/local/bin
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/{{ credhub_version }}/credhub-linux-amd64-{{ credhub_version }}.tgz"
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts:
      - --wildcards
      - '*/credhub'
    mode: '0755'

- name: credhub version
  shell: /usr/local/bin/credhub --version
  register: credhub_version_output
  changed_when: false

- name: show credhub version
  debug:
    msg: "{{ credhub_version_output.stdout }}"
