---
golang_version: 1.23.8
user: adamz
cookie: top_secret
docker_registry_auth: "{{ (lookup('file', '~/.docker/config.json') | from_json).auths['https://index.docker.io/v1/'].auth }}"

tools:
- jq
- tree
- git
- inotify-tools
- curl
- cowsay
