---
- name: make sure target file not present
  become: true
  ansible.builtin.file:
    path: "/tmp/nats-{{ nats_version }}-linux-amd64.zip"
    state: absent

- name: make sure target folder not present
  become: true
  ansible.builtin.file:
    path: "/tmp/nats-{{ nats_version }}-linux-amd64"
    state: absent

- name: download nats
  get_url:
    url: "https://github.com/nats-io/natscli/releases/download/v{{ nats_version }}/nats-{{ nats_version }}-linux-amd64.zip"
    dest: "/tmp/nats-{{ nats_version }}-linux-amd64.zip"

- name: unzip nats
  become: true
  shell: unzip "/tmp/nats-{{ nats_version }}-linux-amd64.zip" -d /tmp

- name: move nats to bin folder
  become: true
  shell: mv "/tmp/nats-{{ nats_version }}-linux-amd64/nats" /usr/local/bin/nats

- name: delete tmp zip file
  become: true
  ansible.builtin.file:
    path: "/tmp/nats-{{ nats_version }}-linux-amd64.zip"
    state: absent

- name: delete tmp zip folder
  become: true
  ansible.builtin.file:
    path: "/tmp/nats-{{ nats_version }}-linux-amd64"
    state: absent
