---
- name: Download and extract nats-server directly to /usr/local/bin
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/nats-io/nats-server/releases/download/v{{ nats_server_version }}/nats-server-v{{ nats_server_version }}-linux-{{ arch }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts:
      - --strip-components=1
      - --wildcards
      - '*/nats-server'
    mode: '0755'

- name: nats-server version
  shell: /usr/local/bin/nats-server --version
  register: nats_server_version_output
  changed_when: false

- name: show nats-server version
  debug:
    msg: "{{ nats_server_version_output.stdout }}"
