---
- name: Download and extract nkey zip to tmp
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/nats-io/nkeys/releases/download/v{{ nkey_version }}/nkeys-v{{ nkey_version }}-linux-{{ arch }}.zip"
    dest: /tmp/
    remote_src: yes

- name: Copy nk binary to /usr/local/bin
  become: true
  ansible.builtin.copy:
    src: "/tmp/nkeys-v{{ nkey_version }}-linux-{{ arch }}/nk"
    dest: /usr/local/bin/nk
    remote_src: yes
    mode: '0755'

- name: nk version
  shell: /usr/local/bin/nk -v
  register: nk_version_output
  changed_when: false

- name: show nk version
  debug:
    msg: "{{ nk_version_output.stdout }}"
