---
- name: Download and extract nsc zip to tmp
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/nats-io/nsc/releases/download/v{{ nsc_version }}/nsc-linux-{{ arch }}.zip"
    dest: /tmp/
    remote_src: yes

- name: Copy nsc binary to /usr/local/bin
  become: true
  ansible.builtin.copy:
    src: /tmp/nsc
    dest: /usr/local/bin/nsc
    remote_src: yes
    mode: '0755'

- name: nsc version
  shell: /usr/local/bin/nsc --version
  register: nsc_version_output
  changed_when: false

- name: show nsc version
  debug:
    msg: "{{ nsc_version_output.stdout }}"
