---
- name: Download and install kubectl
  become: true
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: kubectl version
  shell: /usr/local/bin/kubectl version --client
  register: kubectl_version_output
  changed_when: false
  ignore_errors: yes

- name: show kubectl version
  debug:
    msg: "{{ kubectl_version_output.stdout }}"
