---
- name: Download and install bbl
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/cloudfoundry/bosh-bootloader/releases/download/v{{ bbl_version }}/bbl-v{{ bbl_version }}_linux_amd64"
    dest: /usr/local/bin/bbl
    mode: '0755'

- name: bbl version
  shell: /usr/local/bin/bbl --version
  register: bbl_version_output
  changed_when: false

- name: show bbl version
  debug:
    msg: "{{ bbl_version_output.stdout }}"
