---
- name: Download and extract terraform directly to /usr/local/bin
  become: true
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'

- name: terraform version
  shell: /usr/local/bin/terraform --version
  register: terraform_version_output
  changed_when: false

- name: show terraform version
  debug:
    msg: "{{ terraform_version_output.stdout }}"
