---
- name: Download and install bosh-cli
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/cloudfoundry/bosh-cli/releases/download/v{{ bosh_version }}/bosh-cli-{{ bosh_version }}-linux-amd64"
    dest: /usr/local/bin/bosh
    mode: '0755'

- name: bosh version
  shell: /usr/local/bin/bosh --version
  register: bosh_version_output
  changed_when: false

- name: show bosh version
  debug:
    msg: "{{ bosh_version_output.stdout }}"
